server:
  port: 8004
spring:
  application:
    name: crowd-project
  redis:
    host: 101.132.45.198
    password: 614521hh
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://101.132.45.198:8000/eureka/
aliyun:
  oss:
    end-point: xxx
    bucket-name: xxx
    bucket-domain: xxx
    access-key-secret: xxx
    access-key-id: xxx
